[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
build_flags =
    -I include
    -I ../shared
lib_deps = 
    bblanchon/ArduinoJson @ ^7.0.4
    knolleary/PubSubClient @ ^2.8
    adafruit/Adafruit GFX Library @ ^1.11.11
    adafruit/Adafruit ILI9341 @ ^1.6.1
    ricmoo/QRCode @ ^0.0.1
    tzapu/WiFiManager @ ^2.0.16-rc.2
